### ISSUE TITLE
Mismatch between menu on left and the criterion chosen

### ISSUE THREAD

**Issue by KarinInWinnipeg** [w3c/wai-wcag-quickref#174] opened 2018-09-08 04:51 UTC
In the WCAG Quick Reference, when I click a criterion on the left, the right panel displays it, but the wrong item is darkened/selected on the left side. Very confusing. Attaching a picture. In the example, I had just clicked 1.2.4, which worked to jump to that content, but the menu shows 1.2.3.

In case it's relevant, I had two filters on: WCAG 2.0 and A/AA only (no AAA). 

Please let me know if this is just my misunderstanding with how this is supposed to work.

![mismatch between active portion of page and dark blue menu item](https://user-images.githubusercontent.com/43084499/45250437-a4201680-b2f8-11e8-9a91-f2575a49f546.PNG)

**Comment by yatil** [comment] 2018-09-08 08:08
@KarinInWinnipeg You’re right, the marking on the left is off. I’ll investigate and fix it asap. Sorry for the confusion.

**Comment by yatil** [comment] 2019-06-03 13:55
I tested it now and I could not reproduce. I did make some changes in the meantime, so maybe I just forgot to close the issue :-)

**Closed as completed by yatil** 2019-06-03 13:55 UTC
Labels: bug
