### ISSUE TITLE
Missing data about H98 and F107

### ISSUE THREAD

**Issue by mattsheppard** [w3c/wai-wcag-quickref#204] opened 2020-02-10 06:49 UTC
According to https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose there are two techniques defined for success criterion 1.3.5 - https://www.w3.org/WAI/WCAG21/Techniques/html/H98 and https://www.w3.org/WAI/WCAG21/Techniques/failures/F107, however they are not represented in https://github.com/w3c/wai-wcag-quickref/blob/gh-pages/_data/wcag21.json#L1641

I might be able to try to create a PR to address that if it's agreed that it's an oversight.

**Comment by yatil** [comment] 2020-02-10 08:53
Hi @mattsheppard, thanks for offering to add a Pull Request. This issue will be closed when #201 is addressed.

**Comment by iadawn** [comment] 2024-08-02 16:27
Duplicate of #247 - well ok, this one came first

Should be fixed with 9ebe631

**Closed as completed by iadawn** 2024-08-02 16:27 UTC
Labels: duplicate
